name: Compile and test against PR

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci]')"
    strategy:
      fail-fast: false
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "SCRIPTS_PATH=$(pwd)" >> $GITHUB_ENV
          echo "PLUGIN_NAME_ENV=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: ./scripting/${{ env.PLUGIN_NAME_ENV }}.sp
      
      - name: Download the includes downloader
        run: |
          gh release download --repo Zabaniya001/SPDependy --pattern "SPDependyLinux"
          chmod +x SPDependyLinux
        working-directory: ${{ env.SCRIPTS_PATH }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install SourcePawn includes.
        run: ./SPDependyLinux
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Install linux dependency for toml
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Compile plugins
        run: |
          mkdir plugins
          for plugin in $(jq -r '.Compile.plugins[]' sp.toml); do
            spcomp -w234 -O2 -v2 -i"scripting/include" -i".temp/include" -o"plugins/${plugin}.smx" "scripting/${plugin}.sp"
          done
        working-directory: ${{ env.SCRIPTS_PATH }}