name: Compile and test against PR

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "SCRIPTS_PATH=$(pwd)" >> $GITHUB_ENV
          echo "PLUGIN_NAME_ENV=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: ./scripting/${{ env.PLUGIN_NAME_ENV }}.sp
      
      - name: Download the includes downloader
        run: |
          gh release download --repo Zabaniya001/SPDependy --pattern "SPDependyLinux"
          chmod +x SPDependyLinux
        working-directory: ${{ env.SCRIPTS_PATH }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install the SourcePawn includes.
        run: ./SPDependyLinux ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ env.SCRIPTS_PATH }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Download toml parser
        run: |
          pip install jq
          pip install yq

      - name: Compile plugins
        run: |
          mkdir plugins
          for plugin in $(tomlq '.Compile.plugins[]' sp.toml | cut -d'"' -f2); do
            spcomp -w234 -O2 -v2 -i"scripting/include" -i".temp/include" -o"plugins/${plugin}.smx" "scripting/${plugin}.sp"
          done
        working-directory: ${{ env.SCRIPTS_PATH }}