name: Compile and release

on:
  workflow_dispatch:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install dependencies
        run: go mod download
        working-directory: ${{ env.SCRIPTS_PATH }}
      
      - name: Compile.
        run: |
          set GOARCH=amd64
          set GOOS=linux
          go build -o SPDependyLinux

          set GOARCH=amd64
          set GOOS=windows
          go build -o SPDependyWin.exe
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: manual
          artifacts: "SPDependyWin.exe,SPDependyLinux"
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          allowUpdates: true
          prerelease: false
          replacesArtifacts: true